### ISSUE TITLE
Math overflow error

### ISSUE THREAD

**Issue by DavidS** [hotosm/osm-tasking-manager#86]
On the same installation as #85, I get a math overflow:

```
Traceback (most recent call last):
  File "/srv/osmtm/env/lib/python2.6/site-packages/pyramid-1.3.2-py2.6.egg/pyramid/mako_templating.py", line 181, in __call__
    result = template.render_unicode(**system)
  File "/srv/osmtm/env/lib/python2.6/site-packages/Mako-0.7.2-py2.6.egg/mako/template.py", line 421, in render_unicode
    as_unicode=True)
  File "/srv/osmtm/env/lib/python2.6/site-packages/Mako-0.7.2-py2.6.egg/mako/runtime.py", line 766, in _render
    **_kwargs_for_callable(callable_, data))
  File "/srv/osmtm/env/lib/python2.6/site-packages/Mako-0.7.2-py2.6.egg/mako/runtime.py", line 798, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/srv/osmtm/env/lib/python2.6/site-packages/Mako-0.7.2-py2.6.egg/mako/runtime.py", line 824, in _exec_template
    callable_(context, *args, **kwargs)
  File "/srv/osmtm/env/lib/python2.6/site-packages/OSMTM-0.0-py2.6.egg/OSMTM/templates/task.mako", line 32, in render_body
    <%include file="task.comments.mako" />
  File "/srv/osmtm/env/lib/python2.6/site-packages/Mako-0.7.2-py2.6.egg/mako/runtime.py", line 693, in _include_file
    callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
  File "/srv/osmtm/env/lib/python2.6/site-packages/OSMTM-0.0-py2.6.egg/OSMTM/templates/task.comments.mako", line 21, in render_body
    <%
  File "/srv/osmtm/env/lib/python2.6/site-packages/OSMTM-0.0-py2.6.egg/OSMTM/models.py", line 71, in to_polygon
    return tb.create_square(self.x, self.y, srs)
  File "/srv/osmtm/env/lib/python2.6/site-packages/OSMTM-0.0-py2.6.egg/OSMTM/utils.py", line 26, in create_square
    xmin, ymin = transform_900913_to_4326(xmin, ymin)
  File "/srv/osmtm/env/lib/python2.6/site-packages/OSMTM-0.0-py2.6.egg/OSMTM/utils.py", line 62, in transform_900913_to_4326
    lat = 180/pi * (2 * atan(exp(lat * pi / 180)) -
OverflowError: math range error
```

Here's the pertinent expresson from the interactive debugging page (awesome, isn't it?):

```
>>> exp(lat * pi / 180)
Traceback (most recent call last):
  File "/srv/osmtm/env/lib/python2.6/site-packages/WebError-0.10.3-py2.6.egg/weberror/evalcontext.py", line 35, in exec_expr
    exec code in self.namespace, self.globs
  File "<web>", line 1, in <module>
OverflowError: math range error


lat 3852359.9998461949
lon 3215879.9998716065
x   357990123988.14728
y   428842753475.55847
```

I can PM you the live URL if you want it.

**Comment by pgiraud** [comment]
As I can remember, this was fixed.
